# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name_plural': 'Leads'},
        ),
    ]
