# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20160705_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='notes',
        ),
    ]
