# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_leads_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
