# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20160721_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='has_contacted',
        ),
    ]
