# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='leadgen_form_id',
            new_name='form_id',
        ),
    ]
