# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160702_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cell_phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='form_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
