# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20160702_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='form_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='leadforms',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
