# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20160711_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadforms',
            name='client',
        ),
        migrations.DeleteModel(
            name='LeadForms',
        ),
    ]
