# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20160711_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='form_id',
            new_name='facebook_form_id',
        ),
        migrations.AddField(
            model_name='client',
            name='has_mailchimp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='mailchimp_api',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='mailchimp_dc',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='mailchimp_list',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
