# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20160718_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_drivecentric',
            field=models.BooleanField(default=False),
        ),
    ]
