# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20160721_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 21, 22, 11, 31, 9630, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
