# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_client_drivecentric_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='drivecentric_email',
            new_name='adf_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='has_drivecentric',
            new_name='has_adf_crm',
        ),
    ]
