# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20160728_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
