# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_client_facebook_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='has_mailchimp',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mailchimp_api',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mailchimp_dc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mailchimp_list',
        ),
    ]
