# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_auto_20160628_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='leadgen_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
