# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_newlead_leadgen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlead',
            name='form_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
