# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0006_auto_20160702_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='ad_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
